version: '3.8'

services:
  frontend:
    build:
      context: ./client  # Change this line
      dockerfile: Dockerfile  # Change this line
    ports:
      - "80:80"
    environment:
      - VITE_BACKEND_URL=/api
    depends_on:
      - backend
    restart: unless-stopped

  backend:
    build:
      context: ./server  # Change this line
      dockerfile: Dockerfile  # Change this line
    ports:
      - "8000:8000"
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - KAFKA_BOOTSTRAP_SERVERS=${KAFKA_BOOTSTRAP_SERVERS}
      - KAFKA_TASK_TOPIC=${KAFKA_TASK_TOPIC}
      - KAFKA_TASK_DUE_TOPIC=${KAFKA_TASK_DUE_TOPIC}
      - SENDGRID_API_KEY=${SENDGRID_API_KEY}
      - SENDGRID_FROM_EMAIL=${SENDGRID_FROM_EMAIL}
      - SENDGRID_TEMPLATE_ID=${SENDGRID_TEMPLATE_ID}
      - DATABASE_URL=${DATABASE_URL}
      - ACCESS_TOKEN_EXPIRE_MINUTES=${ACCESS_TOKEN_EXPIRE_MINUTES}
      - ALGORITHM=${ALGORITHM}
    volumes:
      - ./server/todo.db:/app/todo.db
    restart: unless-stopped